// Strings for the popup and the welcome page (the in-game strings live in i18n.js).
var OGW_UI = {
  en: { tagline: 'Shows how long until your planet has enough resources to build.', howTitle: 'How to use', how1: 'Open any building, research, ship or defence in OGame.', how2: 'Under the build info you will see when the resources will be ready.', how3: 'Hover the ? icon for a detailed breakdown.', lang: 'Language', auto: 'Auto (game language)', support: 'Support the developer', supportNote: 'Resource Timer is free. If it saves you time, you can buy me a coffee ☕', welcome: 'Thanks for installing Resource Timer!', story: 'I made this for myself, and OGame got so much better once I always knew *exactly* when I could build next. I hope it helps you too.', unofficial: 'Unofficial fan project. Not affiliated with Gameforge.' },
  de: { tagline: 'Zeigt, wie lange es dauert, bis dein Planet genug Ressourcen zum Bauen hat.', howTitle: 'So funktioniert es', how1: 'Öffne in OGame ein Gebäude, eine Forschung, ein Schiff oder eine Verteidigung.', how2: 'Unter den Bauinfos siehst du, wann die Ressourcen verfügbar sind.', how3: 'Fahre über das ?-Symbol für eine detaillierte Aufstellung.', lang: 'Sprache', auto: 'Automatisch (Spielsprache)', support: 'Entwickler unterstützen', supportNote: 'Resource Timer ist kostenlos. Wenn er dir Zeit spart, kannst du mir einen Kaffee ausgeben ☕', welcome: 'Danke, dass du Resource Timer installiert hast!', story: 'Ich habe das für mich selbst gebaut – und OGame wurde so viel besser, seit ich immer *genau* weiß, wann ich als Nächstes bauen kann. Ich hoffe, es hilft dir auch.', unofficial: 'Inoffizielles Fanprojekt. Nicht mit Gameforge verbunden.' },
  fr: { tagline: 'Indique combien de temps il faut avant que ta planète ait assez de ressources pour construire.', howTitle: 'Comment l\'utiliser', how1: 'Ouvre un bâtiment, une recherche, un vaisseau ou une défense dans OGame.', how2: 'Sous les infos de construction, tu verras quand les ressources seront prêtes.', how3: 'Survole l\'icône ? pour le détail.', lang: 'Langue', auto: 'Auto (langue du jeu)', support: 'Soutenir le développeur', supportNote: 'Resource Timer est gratuit. S\'il te fait gagner du temps, tu peux m\'offrir un café ☕', welcome: 'Merci d\'avoir installé Resource Timer !', story: 'Je l\'ai créé pour moi-même, et OGame est devenu tellement plus agréable depuis que je sais *exactement* quand je peux construire. J\'espère qu\'il t\'aidera aussi.', unofficial: 'Projet de fan non officiel. Non affilié à Gameforge.' },
  es: { tagline: 'Muestra cuánto falta para que tu planeta tenga recursos suficientes para construir.', howTitle: 'Cómo usarlo', how1: 'Abre cualquier edificio, investigación, nave o defensa en OGame.', how2: 'Debajo de la información de construcción verás cuándo estarán listos los recursos.', how3: 'Pasa el ratón por el icono ? para ver el detalle.', lang: 'Idioma', auto: 'Automático (idioma del juego)', support: 'Apoya al desarrollador', supportNote: 'Resource Timer es gratis. Si te ahorra tiempo, puedes invitarme a un café ☕', welcome: '¡Gracias por instalar Resource Timer!', story: 'Lo hice para mí mismo, y OGame mejoró muchísimo desde que siempre sé *exactamente* cuándo puedo construir. Espero que a ti también te ayude.', unofficial: 'Proyecto no oficial de un fan. Sin relación con Gameforge.' },
  it: { tagline: 'Mostra quanto manca prima che il tuo pianeta abbia abbastanza risorse per costruire.', howTitle: 'Come si usa', how1: 'Apri un edificio, una ricerca, una nave o una difesa in OGame.', how2: 'Sotto le informazioni di costruzione vedrai quando le risorse saranno pronte.', how3: 'Passa sopra l\'icona ? per il dettaglio.', lang: 'Lingua', auto: 'Automatica (lingua del gioco)', support: 'Sostieni lo sviluppatore', supportNote: 'Resource Timer è gratuito. Se ti fa risparmiare tempo, puoi offrirmi un caffè ☕', welcome: 'Grazie per aver installato Resource Timer!', story: 'L\'ho creato per me stesso, e OGame è diventato molto più piacevole da quando so sempre *esattamente* quando posso costruire. Spero che aiuti anche te.', unofficial: 'Progetto non ufficiale di un fan. Non affiliato a Gameforge.' },
  pl: { tagline: 'Pokazuje, ile czasu zostało, aż planeta zgromadzi surowce na budowę.', howTitle: 'Jak używać', how1: 'Otwórz w OGame dowolny budynek, badanie, statek lub obronę.', how2: 'Pod informacjami o budowie zobaczysz, kiedy surowce będą gotowe.', how3: 'Najedź na ikonę ?, aby zobaczyć szczegóły.', lang: 'Język', auto: 'Automatycznie (język gry)', support: 'Wesprzyj autora', supportNote: 'Resource Timer jest darmowy. Jeśli oszczędza Ci czas, możesz postawić mi kawę ☕', welcome: 'Dzięki za zainstalowanie Resource Timer!', story: 'Zrobiłem to dla siebie, a OGame stało się o wiele przyjemniejsze, odkąd zawsze wiem *dokładnie*, kiedy mogę budować dalej. Mam nadzieję, że Tobie też pomoże.', unofficial: 'Nieoficjalny projekt fana. Niezwiązany z Gameforge.' },
  pt: { tagline: 'Mostra quanto falta para o teu planeta ter recursos suficientes para construir.', howTitle: 'Como usar', how1: 'Abre qualquer edifício, pesquisa, nave ou defesa no OGame.', how2: 'Por baixo da informação de construção verás quando os recursos estarão prontos.', how3: 'Passa o rato sobre o ícone ? para ver o detalhe.', lang: 'Idioma', auto: 'Automático (idioma do jogo)', support: 'Apoiar o programador', supportNote: 'O Resource Timer é gratuito. Se te poupa tempo, podes pagar-me um café ☕', welcome: 'Obrigado por instalares o Resource Timer!', story: 'Fiz isto para mim, e o OGame ficou muito melhor desde que sei sempre *exatamente* quando posso construir. Espero que te ajude também.', unofficial: 'Projeto não oficial de um fã. Sem ligação à Gameforge.' },
  ru: { tagline: 'Показывает, сколько ждать, пока на планете накопятся ресурсы для постройки.', howTitle: 'Как пользоваться', how1: 'Откройте в OGame любую постройку, исследование, корабль или оборону.', how2: 'Под информацией о постройке появится время, когда накопятся ресурсы.', how3: 'Наведите на значок ?, чтобы увидеть подробности.', lang: 'Язык', auto: 'Авто (язык игры)', support: 'Поддержать автора', supportNote: 'Resource Timer бесплатный. Если он экономит вам время, можно угостить меня кофе ☕', welcome: 'Спасибо, что установили Resource Timer!', story: 'Я сделал его для себя — и играть в OGame стало намного приятнее, когда я всегда *точно* знаю, когда смогу строить дальше. Надеюсь, вам он тоже поможет.', unofficial: 'Неофициальный фанатский проект. Не связан с Gameforge.' },
  tr: { tagline: 'Gezegeninin inşa için yeterli kaynağa ne zaman ulaşacağını gösterir.', howTitle: 'Nasıl kullanılır', how1: 'OGame\'de herhangi bir bina, araştırma, gemi veya savunma aç.', how2: 'İnşa bilgilerinin altında kaynakların ne zaman hazır olacağını göreceksin.', how3: 'Ayrıntılar için ? simgesinin üzerine gel.', lang: 'Dil', auto: 'Otomatik (oyun dili)', support: 'Geliştiriciyi destekle', supportNote: 'Resource Timer ücretsizdir. Zamanını kurtarıyorsa bana bir kahve ısmarlayabilirsin ☕', welcome: 'Resource Timer\'ı yüklediğin için teşekkürler!', story: 'Bunu kendim için yaptım ve bir sonraki inşaatı *tam olarak* ne zaman yapabileceğimi bildiğimden beri OGame çok daha keyifli hale geldi. Umarım sana da yardımcı olur.', unofficial: 'Resmi olmayan hayran projesi. Gameforge ile bağlantılı değildir.' },
  nl: { tagline: 'Toont hoe lang het duurt tot je planeet genoeg grondstoffen heeft om te bouwen.', howTitle: 'Zo werkt het', how1: 'Open in OGame een gebouw, onderzoek, schip of verdediging.', how2: 'Onder de bouwinformatie zie je wanneer de grondstoffen klaar zijn.', how3: 'Beweeg over het ?-icoon voor een gedetailleerd overzicht.', lang: 'Taal', auto: 'Automatisch (speltaal)', support: 'Steun de ontwikkelaar', supportNote: 'Resource Timer is gratis. Bespaart het je tijd, dan kun je me een koffie trakteren ☕', welcome: 'Bedankt voor het installeren van Resource Timer!', story: 'Ik heb dit voor mezelf gemaakt, en OGame werd zoveel leuker sinds ik altijd *precies* weet wanneer ik weer kan bouwen. Ik hoop dat het jou ook helpt.', unofficial: 'Onofficieel fanproject. Niet verbonden aan Gameforge.' },
  cs: { tagline: 'Ukazuje, jak dlouho potrvá, než bude mít planeta dost surovin na stavbu.', howTitle: 'Jak používat', how1: 'Otevři v OGame libovolnou budovu, výzkum, loď nebo obranu.', how2: 'Pod informacemi o stavbě uvidíš, kdy budou suroviny připravené.', how3: 'Najeď na ikonu ? pro podrobný rozpis.', lang: 'Jazyk', auto: 'Automaticky (jazyk hry)', support: 'Podpořit autora', supportNote: 'Resource Timer je zdarma. Pokud ti šetří čas, můžeš mi koupit kávu ☕', welcome: 'Díky za instalaci Resource Timer!', story: 'Udělal jsem ho pro sebe a OGame mě začalo bavit mnohem víc, když vždy *přesně* vím, kdy můžu stavět dál. Doufám, že pomůže i tobě.', unofficial: 'Neoficiální fanouškovský projekt. Bez vazby na Gameforge.' },
  sk: { tagline: 'Ukazuje, ako dlho potrvá, kým bude mať planéta dosť surovín na stavbu.', howTitle: 'Ako používať', how1: 'Otvor v OGame ľubovoľnú budovu, výskum, loď alebo obranu.', how2: 'Pod informáciami o stavbe uvidíš, kedy budú suroviny pripravené.', how3: 'Prejdi myšou na ikonu ? pre podrobný rozpis.', lang: 'Jazyk', auto: 'Automaticky (jazyk hry)', support: 'Podporiť autora', supportNote: 'Resource Timer je zadarmo. Ak ti šetrí čas, môžeš mi kúpiť kávu ☕', welcome: 'Vďaka za inštaláciu Resource Timer!', story: 'Urobil som ho pre seba a OGame ma začalo baviť oveľa viac, keď vždy *presne* viem, kedy môžem stavať ďalej. Dúfam, že pomôže aj tebe.', unofficial: 'Neoficiálny fanúšikovský projekt. Bez prepojenia s Gameforge.' },
  hu: { tagline: 'Megmutatja, mennyi idő múlva lesz elég nyersanyag a bolygódon az építéshez.', howTitle: 'Használat', how1: 'Nyiss meg az OGame-ben bármilyen épületet, kutatást, hajót vagy védelmet.', how2: 'Az építési adatok alatt látod, mikor lesz kész a nyersanyag.', how3: 'Vidd az egeret a ? ikonra a részletekért.', lang: 'Nyelv', auto: 'Automatikus (játék nyelve)', support: 'Támogasd a fejlesztőt', supportNote: 'A Resource Timer ingyenes. Ha időt spórol neked, meghívhatsz egy kávéra ☕', welcome: 'Köszönöm, hogy telepítetted a Resource Timert!', story: 'Magamnak készítettem, és az OGame sokkal jobb lett, mióta mindig *pontosan* tudom, mikor építhetek legközelebb. Remélem, neked is segít.', unofficial: 'Nem hivatalos rajongói projekt. Nem kapcsolódik a Gameforge-hoz.' },
  ro: { tagline: 'Arată cât mai durează până când planeta ta are suficiente resurse pentru construcție.', howTitle: 'Cum se folosește', how1: 'Deschide în OGame orice clădire, cercetare, navă sau apărare.', how2: 'Sub informațiile de construcție vei vedea când vor fi gata resursele.', how3: 'Treci cu mouse-ul peste pictograma ? pentru detalii.', lang: 'Limbă', auto: 'Automat (limba jocului)', support: 'Susține dezvoltatorul', supportNote: 'Resource Timer este gratuit. Dacă îți economisește timp, îmi poți face cinste cu o cafea ☕', welcome: 'Mulțumesc că ai instalat Resource Timer!', story: 'L-am făcut pentru mine, iar OGame a devenit mult mai plăcut de când știu mereu *exact* când pot construi din nou. Sper să te ajute și pe tine.', unofficial: 'Proiect neoficial al unui fan. Neafiliat cu Gameforge.' },
  el: { tagline: 'Δείχνει πόσο θα πάρει μέχρι ο πλανήτης σου να έχει αρκετούς πόρους για κατασκευή.', howTitle: 'Πώς λειτουργεί', how1: 'Άνοιξε στο OGame οποιοδήποτε κτίριο, έρευνα, πλοίο ή άμυνα.', how2: 'Κάτω από τις πληροφορίες κατασκευής θα δεις πότε θα είναι έτοιμοι οι πόροι.', how3: 'Πέρασε τον δείκτη πάνω από το εικονίδιο ? για λεπτομέρειες.', lang: 'Γλώσσα', auto: 'Αυτόματα (γλώσσα παιχνιδιού)', support: 'Στήριξε τον δημιουργό', supportNote: 'Το Resource Timer είναι δωρεάν. Αν σου γλιτώνει χρόνο, μπορείς να με κεράσεις έναν καφέ ☕', welcome: 'Ευχαριστώ που εγκατέστησες το Resource Timer!', story: 'Το έφτιαξα για μένα, και το OGame έγινε πολύ καλύτερο από τότε που ξέρω πάντα *ακριβώς* πότε μπορώ να χτίσω ξανά. Ελπίζω να βοηθήσει και εσένα.', unofficial: 'Ανεπίσημο έργο θαυμαστή. Χωρίς σχέση με την Gameforge.' },
  da: { tagline: 'Viser, hvor længe der går, før din planet har ressourcer nok til at bygge.', howTitle: 'Sådan bruger du den', how1: 'Åbn en bygning, forskning, et skib eller et forsvar i OGame.', how2: 'Under byggeinfo kan du se, hvornår ressourcerne er klar.', how3: 'Hold musen over ?-ikonet for en detaljeret oversigt.', lang: 'Sprog', auto: 'Automatisk (spillets sprog)', support: 'Støt udvikleren', supportNote: 'Resource Timer er gratis. Sparer den dig tid, kan du give mig en kop kaffe ☕', welcome: 'Tak fordi du installerede Resource Timer!', story: 'Jeg lavede den til mig selv, og OGame blev så meget bedre, da jeg altid vidste *præcis*, hvornår jeg kunne bygge igen. Jeg håber, den hjælper dig også.', unofficial: 'Uofficielt fanprojekt. Ikke tilknyttet Gameforge.' },
  sv: { tagline: 'Visar hur länge det dröjer tills din planet har tillräckligt med resurser för att bygga.', howTitle: 'Så här fungerar det', how1: 'Öppna en byggnad, forskning, ett skepp eller ett försvar i OGame.', how2: 'Under bygginformationen ser du när resurserna är klara.', how3: 'Håll muspekaren över ?-ikonen för en detaljerad översikt.', lang: 'Språk', auto: 'Automatiskt (spelets språk)', support: 'Stöd utvecklaren', supportNote: 'Resource Timer är gratis. Om den sparar dig tid kan du bjuda mig på en kaffe ☕', welcome: 'Tack för att du installerade Resource Timer!', story: 'Jag gjorde den till mig själv, och OGame blev så mycket bättre när jag alltid visste *exakt* när jag kunde bygga nästa gång. Jag hoppas att den hjälper dig också.', unofficial: 'Inofficiellt fanprojekt. Inte knutet till Gameforge.' },
  hr: { tagline: 'Pokazuje koliko treba dok tvoj planet ne skupi dovoljno resursa za gradnju.', howTitle: 'Kako koristiti', how1: 'Otvori u OGameu bilo koju zgradu, istraživanje, brod ili obranu.', how2: 'Ispod informacija o gradnji vidjet ćeš kada će resursi biti spremni.', how3: 'Prijeđi mišem preko ikone ? za detaljan prikaz.', lang: 'Jezik', auto: 'Automatski (jezik igre)', support: 'Podrži autora', supportNote: 'Resource Timer je besplatan. Ako ti štedi vrijeme, možeš me častiti kavom ☕', welcome: 'Hvala što si instalirao Resource Timer!', story: 'Napravio sam ga za sebe i OGame je postao puno bolji otkad uvijek *točno* znam kada mogu sljedeće graditi. Nadam se da će pomoći i tebi.', unofficial: 'Neslužbeni projekt obožavatelja. Nije povezan s Gameforgeom.' }
};

// Language for extension pages: the user's choice, else the browser language.
function ogwUiLang(override) {
  if (override && OGW_UI[override]) return override;
  var c = (navigator.language || 'en').toLowerCase().slice(0, 2);
  c = OGW_LANG_ALIASES[c] || c;
  return OGW_UI[c] ? c : 'en';
}

// Fills every [data-i18n] element on an extension page.
function ogwTranslatePage(lang) {
  var t = OGW_UI[lang];
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    // *word* is highlighted in green with a check mark.
    var parts = t[el.getAttribute('data-i18n')].split('*');
    el.replaceChildren();
    parts.forEach(function (part, i) {
      if (i % 2 === 0) { el.append(part); return; }
      var hl = document.createElement('span');
      hl.className = 'hl';
      hl.textContent = '✓ ' + part;
      el.append(hl);
    });
  });
}

// Strings for the support (donation) page, merged into OGW_UI.
var OGW_SUPPORT_UI = {
  en: { sTitle: 'Support Resource Timer', sIntro: 'The extension is free and always will be. Pick whatever is easiest for you — every coffee keeps the updates coming. Thank you!', sRec: 'Recommended', sKofi: 'Card or PayPal', sKofiDesc: 'Via Ko-fi. No account needed — pay with any bank card or PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Straight to PayPal, if you already have an account.', sCrypto: 'Crypto', sNet: 'Network', sCryptoWarn: 'Send only the coin shown, on the network shown — otherwise the funds will be lost.', sCopy: 'Copy', sCopied: 'Copied!' },
  de: { sTitle: 'Resource Timer unterstützen', sIntro: 'Die Erweiterung ist kostenlos und bleibt es auch. Wähle, was für dich am einfachsten ist – jeder Kaffee hält die Updates am Laufen. Danke!', sRec: 'Empfohlen', sKofi: 'Karte oder PayPal', sKofiDesc: 'Über Ko-fi. Kein Konto nötig – zahle mit jeder Bankkarte oder PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Direkt über PayPal, wenn du schon ein Konto hast.', sCrypto: 'Krypto', sNet: 'Netzwerk', sCryptoWarn: 'Sende nur die angegebene Coin im angegebenen Netzwerk – sonst geht das Geld verloren.', sCopy: 'Kopieren', sCopied: 'Kopiert!' },
  fr: { sTitle: 'Soutenir Resource Timer', sIntro: 'L\'extension est gratuite et le restera. Choisis ce qui est le plus simple pour toi — chaque café aide à continuer les mises à jour. Merci !', sRec: 'Recommandé', sKofi: 'Carte ou PayPal', sKofiDesc: 'Via Ko-fi. Aucun compte requis — paie avec n\'importe quelle carte bancaire ou PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Directement sur PayPal, si tu as déjà un compte.', sCrypto: 'Crypto', sNet: 'Réseau', sCryptoWarn: 'Envoie uniquement la crypto indiquée, sur le réseau indiqué — sinon les fonds seront perdus.', sCopy: 'Copier', sCopied: 'Copié !' },
  es: { sTitle: 'Apoya Resource Timer', sIntro: 'La extensión es gratis y siempre lo será. Elige lo que te resulte más fácil: cada café ayuda a que sigan llegando actualizaciones. ¡Gracias!', sRec: 'Recomendado', sKofi: 'Tarjeta o PayPal', sKofiDesc: 'A través de Ko-fi. Sin cuenta: paga con cualquier tarjeta bancaria o PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Directo a PayPal, si ya tienes cuenta.', sCrypto: 'Cripto', sNet: 'Red', sCryptoWarn: 'Envía solo la moneda indicada y en la red indicada; de lo contrario, los fondos se perderán.', sCopy: 'Copiar', sCopied: '¡Copiado!' },
  it: { sTitle: 'Sostieni Resource Timer', sIntro: 'L\'estensione è gratuita e lo resterà. Scegli il modo più comodo per te: ogni caffè aiuta a portare nuovi aggiornamenti. Grazie!', sRec: 'Consigliato', sKofi: 'Carta o PayPal', sKofiDesc: 'Tramite Ko-fi. Nessun account necessario: paga con qualsiasi carta o PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Direttamente su PayPal, se hai già un account.', sCrypto: 'Cripto', sNet: 'Rete', sCryptoWarn: 'Invia solo la moneta indicata, sulla rete indicata, altrimenti i fondi andranno persi.', sCopy: 'Copia', sCopied: 'Copiato!' },
  pl: { sTitle: 'Wesprzyj Resource Timer', sIntro: 'Rozszerzenie jest darmowe i takie zostanie. Wybierz to, co dla Ciebie najwygodniejsze — każda kawa pomaga w kolejnych aktualizacjach. Dziękuję!', sRec: 'Polecane', sKofi: 'Karta lub PayPal', sKofiDesc: 'Przez Ko-fi. Bez zakładania konta — zapłać dowolną kartą lub PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Bezpośrednio przez PayPal, jeśli masz już konto.', sCrypto: 'Krypto', sNet: 'Sieć', sCryptoWarn: 'Wysyłaj tylko podaną walutę w podanej sieci, inaczej środki przepadną.', sCopy: 'Kopiuj', sCopied: 'Skopiowano!' },
  pt: { sTitle: 'Apoiar o Resource Timer', sIntro: 'A extensão é gratuita e assim continuará. Escolhe o que for mais fácil para ti — cada café ajuda a manter as atualizações. Obrigado!', sRec: 'Recomendado', sKofi: 'Cartão ou PayPal', sKofiDesc: 'Via Ko-fi. Sem conta — paga com qualquer cartão bancário ou PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Diretamente pelo PayPal, se já tens conta.', sCrypto: 'Cripto', sNet: 'Rede', sCryptoWarn: 'Envia apenas a moeda indicada, na rede indicada, caso contrário os fundos serão perdidos.', sCopy: 'Copiar', sCopied: 'Copiado!' },
  ru: { sTitle: 'Поддержать Resource Timer', sIntro: 'Расширение бесплатное и останется таким. Выберите самый удобный способ — каждая чашка кофе помогает выпускать обновления. Спасибо!', sRec: 'Рекомендуем', sKofi: 'Картой или PayPal', sKofiDesc: 'Через Ko-fi. Без регистрации — любой банковской картой или PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Напрямую в PayPal, если у вас уже есть аккаунт.', sCrypto: 'Крипта', sNet: 'Сеть', sCryptoWarn: 'Отправляйте только указанную монету в указанной сети, иначе средства пропадут.', sCopy: 'Копировать', sCopied: 'Скопировано!' },
  tr: { sTitle: 'Resource Timer\'ı destekle', sIntro: 'Eklenti ücretsizdir ve öyle kalacak. Sana en kolay geleni seç — her kahve güncellemelerin devam etmesine yardımcı olur. Teşekkürler!', sRec: 'Önerilen', sKofi: 'Kart veya PayPal', sKofiDesc: 'Ko-fi üzerinden. Hesap gerekmez — herhangi bir banka kartı veya PayPal ile öde.', sPaypal: 'PayPal', sPaypalDesc: 'Zaten hesabın varsa doğrudan PayPal ile.', sCrypto: 'Kripto', sNet: 'Ağ', sCryptoWarn: 'Yalnızca belirtilen coini belirtilen ağda gönder, aksi halde para kaybolur.', sCopy: 'Kopyala', sCopied: 'Kopyalandı!' },
  nl: { sTitle: 'Steun Resource Timer', sIntro: 'De extensie is gratis en blijft dat. Kies wat voor jou het makkelijkst is — elke koffie houdt de updates gaande. Bedankt!', sRec: 'Aanbevolen', sKofi: 'Kaart of PayPal', sKofiDesc: 'Via Ko-fi. Geen account nodig — betaal met elke bankkaart of PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Direct via PayPal, als je al een account hebt.', sCrypto: 'Crypto', sNet: 'Netwerk', sCryptoWarn: 'Stuur alleen de aangegeven munt op het aangegeven netwerk, anders gaat het geld verloren.', sCopy: 'Kopiëren', sCopied: 'Gekopieerd!' },
  cs: { sTitle: 'Podpořit Resource Timer', sIntro: 'Rozšíření je zdarma a zůstane zdarma. Vyber, co je pro tebe nejjednodušší — každá káva pomáhá dalším aktualizacím. Díky!', sRec: 'Doporučeno', sKofi: 'Kartou nebo PayPalem', sKofiDesc: 'Přes Ko-fi. Bez účtu — zaplať libovolnou kartou nebo PayPalem.', sPaypal: 'PayPal', sPaypalDesc: 'Přímo přes PayPal, pokud už máš účet.', sCrypto: 'Krypto', sNet: 'Síť', sCryptoWarn: 'Posílej pouze uvedenou měnu v uvedené síti, jinak prostředky propadnou.', sCopy: 'Kopírovat', sCopied: 'Zkopírováno!' },
  sk: { sTitle: 'Podporiť Resource Timer', sIntro: 'Rozšírenie je zadarmo a zostane zadarmo. Vyber, čo je pre teba najjednoduchšie — každá káva pomáha ďalším aktualizáciám. Vďaka!', sRec: 'Odporúčané', sKofi: 'Kartou alebo PayPalom', sKofiDesc: 'Cez Ko-fi. Bez účtu — zaplať ľubovoľnou kartou alebo PayPalom.', sPaypal: 'PayPal', sPaypalDesc: 'Priamo cez PayPal, ak už máš účet.', sCrypto: 'Krypto', sNet: 'Sieť', sCryptoWarn: 'Posielaj iba uvedenú menu v uvedenej sieti, inak prostriedky prepadnú.', sCopy: 'Kopírovať', sCopied: 'Skopírované!' },
  hu: { sTitle: 'Támogasd a Resource Timert', sIntro: 'A bővítmény ingyenes, és az is marad. Válaszd azt, ami neked a legegyszerűbb — minden kávé segít a frissítésekben. Köszönöm!', sRec: 'Ajánlott', sKofi: 'Kártya vagy PayPal', sKofiDesc: 'Ko-fi-n keresztül. Fiók nélkül — fizess bármilyen bankkártyával vagy PayPallal.', sPaypal: 'PayPal', sPaypalDesc: 'Közvetlenül PayPalon, ha már van fiókod.', sCrypto: 'Kripto', sNet: 'Hálózat', sCryptoWarn: 'Csak a megadott coint küldd a megadott hálózaton, különben a pénz elvész.', sCopy: 'Másolás', sCopied: 'Másolva!' },
  ro: { sTitle: 'Susține Resource Timer', sIntro: 'Extensia este gratuită și va rămâne așa. Alege ce îți este cel mai simplu — fiecare cafea ajută la noi actualizări. Mulțumesc!', sRec: 'Recomandat', sKofi: 'Card sau PayPal', sKofiDesc: 'Prin Ko-fi. Fără cont — plătești cu orice card bancar sau PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Direct prin PayPal, dacă ai deja cont.', sCrypto: 'Cripto', sNet: 'Rețea', sCryptoWarn: 'Trimite doar moneda indicată, pe rețeaua indicată, altfel fondurile se pierd.', sCopy: 'Copiază', sCopied: 'Copiat!' },
  el: { sTitle: 'Στήριξε το Resource Timer', sIntro: 'Η επέκταση είναι δωρεάν και θα παραμείνει. Διάλεξε ό,τι σε βολεύει — κάθε καφές βοηθά να συνεχιστούν οι ενημερώσεις. Ευχαριστώ!', sRec: 'Προτεινόμενο', sKofi: 'Κάρτα ή PayPal', sKofiDesc: 'Μέσω Ko-fi. Χωρίς λογαριασμό — πλήρωσε με οποιαδήποτε κάρτα ή PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Απευθείας μέσω PayPal, αν έχεις ήδη λογαριασμό.', sCrypto: 'Κρυπτο', sNet: 'Δίκτυο', sCryptoWarn: 'Στείλε μόνο το νόμισμα που αναφέρεται, στο δίκτυο που αναφέρεται, αλλιώς τα χρήματα θα χαθούν.', sCopy: 'Αντιγραφή', sCopied: 'Αντιγράφηκε!' },
  da: { sTitle: 'Støt Resource Timer', sIntro: 'Udvidelsen er gratis og forbliver det. Vælg det, der er nemmest for dig — hver kop kaffe holder opdateringerne kørende. Tak!', sRec: 'Anbefalet', sKofi: 'Kort eller PayPal', sKofiDesc: 'Via Ko-fi. Ingen konto nødvendig — betal med ethvert betalingskort eller PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Direkte via PayPal, hvis du allerede har en konto.', sCrypto: 'Krypto', sNet: 'Netværk', sCryptoWarn: 'Send kun den viste mønt på det viste netværk, ellers går pengene tabt.', sCopy: 'Kopiér', sCopied: 'Kopieret!' },
  sv: { sTitle: 'Stöd Resource Timer', sIntro: 'Tillägget är gratis och kommer alltid att vara det. Välj det som är enklast för dig — varje kaffe håller uppdateringarna igång. Tack!', sRec: 'Rekommenderas', sKofi: 'Kort eller PayPal', sKofiDesc: 'Via Ko-fi. Inget konto behövs — betala med valfritt bankkort eller PayPal.', sPaypal: 'PayPal', sPaypalDesc: 'Direkt via PayPal, om du redan har ett konto.', sCrypto: 'Krypto', sNet: 'Nätverk', sCryptoWarn: 'Skicka endast den angivna valutan på det angivna nätverket, annars går pengarna förlorade.', sCopy: 'Kopiera', sCopied: 'Kopierat!' },
  hr: { sTitle: 'Podrži Resource Timer', sIntro: 'Proširenje je besplatno i tako će ostati. Odaberi ono što ti je najlakše — svaka kava pomaže novim ažuriranjima. Hvala!', sRec: 'Preporučeno', sKofi: 'Kartica ili PayPal', sKofiDesc: 'Preko Ko-fija. Bez računa — plati bilo kojom bankovnom karticom ili PayPalom.', sPaypal: 'PayPal', sPaypalDesc: 'Izravno preko PayPala, ako već imaš račun.', sCrypto: 'Kripto', sNet: 'Mreža', sCryptoWarn: 'Šalji samo navedenu valutu na navedenoj mreži, inače će sredstva biti izgubljena.', sCopy: 'Kopiraj', sCopied: 'Kopirano!' }
};
for (var ogwL in OGW_SUPPORT_UI) Object.assign(OGW_UI[ogwL], OGW_SUPPORT_UI[ogwL]);

// Footer links (source code / bug reports), merged into OGW_UI.
var OGW_FOOTER_UI = {
  en: { source: 'Source code', bug: 'Report a bug' },
  de: { source: 'Quellcode', bug: 'Fehler melden' },
  fr: { source: 'Code source', bug: 'Signaler un bug' },
  es: { source: 'Código fuente', bug: 'Informar de un error' },
  it: { source: 'Codice sorgente', bug: 'Segnala un bug' },
  pl: { source: 'Kod źródłowy', bug: 'Zgłoś błąd' },
  pt: { source: 'Código-fonte', bug: 'Reportar um erro' },
  ru: { source: 'Исходный код', bug: 'Сообщить об ошибке' },
  tr: { source: 'Kaynak kodu', bug: 'Hata bildir' },
  nl: { source: 'Broncode', bug: 'Bug melden' },
  cs: { source: 'Zdrojový kód', bug: 'Nahlásit chybu' },
  sk: { source: 'Zdrojový kód', bug: 'Nahlásiť chybu' },
  hu: { source: 'Forráskód', bug: 'Hiba bejelentése' },
  ro: { source: 'Cod sursă', bug: 'Raportează o eroare' },
  el: { source: 'Πηγαίος κώδικας', bug: 'Αναφορά σφάλματος' },
  da: { source: 'Kildekode', bug: 'Rapportér en fejl' },
  sv: { source: 'Källkod', bug: 'Rapportera ett fel' },
  hr: { source: 'Izvorni kod', bug: 'Prijavi grešku' }
};
for (var ogwF in OGW_FOOTER_UI) Object.assign(OGW_UI[ogwF], OGW_FOOTER_UI[ogwF]);

// Points the footer's [data-repo] links at the GitHub project.
function ogwFooterLinks() {
  document.querySelectorAll('[data-repo]').forEach(function (a) {
    a.href = OGW_REPO_URL + a.getAttribute('data-repo');
  });
}
